export const TEMPLATE_PROFILES = {
  "Weekend Getaway": {
    key: "weekend",
    pace: "relaxed",
    maxActivitiesPerDay: 4,
    startTime: "10:00",
    dinnerTime: 19,
    restBreak: null,
    preferencePresets: ["Cafes", "Shopping", "Sightseeing"],
    budgetBias: null,
    packingHints: ["Light pack — weekend bag only"],
    packingTags: ["light"],
    chatTone: "weekend",
    chatBias: "low-effort high-reward spots, no museum marathons",
    firstDayShape: "late-start",
    lastDayShape: "early-finish",
  },
  "Family Holiday": {
    key: "family",
    pace: "balanced",
    maxActivitiesPerDay: 5,
    startTime: "09:00",
    dinnerTime: 18,
    restBreak: { from: 13, to: 15 },
    preferencePresets: ["Playgrounds", "Aquariums", "Easy walks", "Ice cream"],
    budgetBias: null,
    packingHints: ["Pack kid essentials"],
    packingTags: ["family"],
    chatTone: "family",
    chatBias: "kid-friendly venues, highchairs, changing facilities, family tickets",
    firstDayShape: "standard",
    lastDayShape: "standard",
    conflictRules: { maxEveningHour: 19, noActivityBefore: 9 },
  },
  "Backpacking": {
    key: "backpacking",
    pace: "packed",
    maxActivitiesPerDay: 6,
    startTime: "07:30",
    dinnerTime: 20,
    restBreak: null,
    preferencePresets: ["Street food", "Hiking", "Markets", "Free attractions"],
    budgetBias: "budget",
    packingHints: ["Pack light — backpack only"],
    packingTags: ["backpacking", "compact"],
    chatTone: "backpacking",
    chatBias: "budget-friendly, free attractions, street food, hostels, walking tours",
    firstDayShape: "early-start",
    lastDayShape: "late-finish",
  },
  "Romantic Trip": {
    key: "romantic",
    pace: "relaxed",
    maxActivitiesPerDay: 3,
    startTime: "10:30",
    dinnerTime: 20,
    restBreak: null,
    preferencePresets: ["Fine dining", "Spa", "Sunset spots", "Wine tasting"],
    budgetBias: "luxury",
    packingHints: ["Smart casual + evening wear"],
    packingTags: ["smart-casual", "evening-wear"],
    chatTone: "romantic",
    chatBias: "upscale venues, cocktail bars, scenic walks, spa, skip fast food/budget options",
    firstDayShape: "late-start",
    lastDayShape: "late-start",
  },
  "Lads/Girls Trip": {
    key: "party",
    pace: "balanced",
    maxActivitiesPerDay: 4,
    startTime: "11:00",
    dinnerTime: 20,
    restBreak: null,
    preferencePresets: ["Nightlife", "Brunch", "Adventure activities", "Sports bars"],
    budgetBias: null,
    packingHints: ["Going-out clothes", "Hangover kit"],
    packingTags: ["nightlife"],
    chatTone: "party",
    chatBias: "nightlife, bars, clubs, brunch spots, adventure activities, group deals",
    firstDayShape: "late-start",
    lastDayShape: "late-start",
  },
  "Road Trip": {
    key: "roadtrip",
    pace: "balanced",
    maxActivitiesPerDay: 4,
    startTime: "08:00",
    dinnerTime: 19,
    restBreak: null,
    preferencePresets: ["Scenic routes", "Roadside attractions", "Local diners"],
    budgetBias: null,
    packingHints: ["Car snacks & drinks", "Road trip playlist"],
    packingTags: ["road-trip"],
    chatTone: "roadtrip",
    chatBias: "scenic stops, roadside attractions, rest areas, local diners, petrol/EV charging",
    firstDayShape: "standard",
    lastDayShape: "standard",
  },
  "Active Adventure": {
    key: "adventure",
    pace: "packed",
    maxActivitiesPerDay: 5,
    startTime: "07:00",
    dinnerTime: 19,
    restBreak: null,
    preferencePresets: ["Hiking", "Cycling", "Kayaking", "Rock climbing"],
    budgetBias: null,
    packingHints: ["Sports gear & layers", "High-energy snacks"],
    packingTags: ["adventure", "sports"],
    chatTone: "adventure",
    chatBias: "outdoor activities, hiking trails, adventure sports, gear rental, hearty meals",
    firstDayShape: "early-start",
    lastDayShape: "standard",
  },
  "Cultural Explorer": {
    key: "cultural",
    pace: "balanced",
    maxActivitiesPerDay: 5,
    startTime: "09:00",
    dinnerTime: 19,
    restBreak: null,
    preferencePresets: ["Museums", "Galleries", "Guided tours", "Local food"],
    budgetBias: null,
    packingHints: ["Comfortable walking shoes", "Notebook/sketchbook"],
    packingTags: ["cultural"],
    chatTone: "cultural",
    chatBias: "museums, galleries, historical tours, local cuisine, architecture, hidden gems",
    firstDayShape: "standard",
    lastDayShape: "standard",
  },
};
